#cloud-config
package_update: false
package_upgrade: false

write_files:
  - path: /opt/portainer/docker-compose.yml
    permissions: '0644'
    content: |
      services:
        portainer:
          image: portainer/portainer-ce:latest
          container_name: portainer
          restart: unless-stopped
          ports:
            - "9443:9443"   # HTTPS UI
            - "8000:8000"   # Edge agent (optional)
          volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - portainer_data:/data
      volumes:
        portainer_data:

  - path: /etc/systemd/system/compose-portainer.service
    permissions: '0644'
    content: |
      [Unit]
      Description=Portainer via Docker Compose
      After=docker.service network-online.target
      Wants=docker.service network-online.target

      [Service]
      Type=oneshot
      RemainAfterExit=yes
      WorkingDirectory=/opt/portainer
      ExecStart=/usr/bin/docker compose up -d
      ExecStop=/usr/bin/docker compose down
      TimeoutStartSec=0

      [Install]
      WantedBy=multi-user.target

runcmd:
  - [ mkdir, -p, /opt/portainer ]
  - [ /bin/systemctl, daemon-reload ]
  - [ /bin/systemctl, enable, --now, compose-portainer.service ]
