version: "3.8"

services:
  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    restart: unless-stopped
    ports:
      - "3001:3001"
    volumes:
      - /opt/uptime-kuma/data:/app/data
    environment:
      # Adjust timezone as needed
      - TZ=America/New_York
